### ISSUE TITLE
PHP 7.1 or 5.4?

### ISSUE THREAD

**Issue by Koenvh1** [DaveRandom/Resume#1]
Hi Chris Wright,

I came here from your StackOverflow post, which mentions that your code runs on PHP 5.4 or later:
https://stackoverflow.com/questions/157318/resumable-downloads-when-using-php-to-send-the-file/4451376#4451376
However, the composer.json in this repository requires PHP 7.1 or later. I'm unfortunately stuck at PHP 7.0 at the moment, and I was wondering:
* whether the required version is PHP 5.4 or 7.1
* and if it does require PHP 7.1, what functionality from 7.1 is used. I only noticed a few nullable types and class constant visibility.

Thank you in advance,

Koen

**Comment by DaveRandom** [comment]
I tend to target 7.1 with most things, but typically the only differences are const visibility, void return, nullable types and possibly short/named array destructuring. It should backport easily to 7.0. I'm mobile right now but will try and look at it tomorrow, if it's not detrimental I can probably tag something that's 7.0 compatible, this lib is pretty stable (I'd actually forgotten it exists :-P)

**Comment by DaveRandom** [comment]
https://github.com/DaveRandom/Resume/releases/tag/v0.0.3 is now usable in 7.0
