### ISSUE TITLE
Cannot pass variable filename

### ISSUE THREAD

**Issue by duckboy81** [DaveRandom/Resume#2]
It appears there is no option to pass a variable filename to the `getAdditionalHeaders()` function.

**Comment by iroegbu** [comment]
If I understand correctly, you want that function to accept a file name different from the one set in constructor? If that is truly what you want, next question will be, why?

**Comment by duckboy81** [comment]
Thanks for the quick reply.

That's correct. As far as why: I store uploaded files with a unique id and
store the original filename in a database. On retrieval I pass the original
filename with the `filename=` header.

What are your thoughts?

**Comment by DaveRandom** [comment]
So am I right in thinking that you have something roughly along the lines of:

```php
$resource = new DatabaseFileResource($fileId);
// ...where DatabaseFileResource is a custom Resource implementation
// which is pulling data from a database
```

...and what you want is to be able to have the browser get the file with the original name as stored in the database?

**Comment by duckboy81** [comment]
You got it!

**Comment by DaveRandom** [comment]
In order to specify the file name you just need to include it as part of the content-disposition header returned by `getAdditionalHeaders()`.

For example, the implementation from the default `FileResource` looks like this:

```php
public function getAdditionalHeaders(): array
{
    return [
        'Content-Disposition' => 'attachment; filename="' . \basename($this->localPath) . '"'
    ];
}
```

You simply need to replace `\basename($this->localPath)` with the file name you have retrieved from the database.

**Comment by DaveRandom** [comment]
Closing this as I believe the above info should resolve your issue, please re-open if you need more assistance.
