### ISSUE TITLE
Wrong Content-Length?

### ISSUE THREAD

**Issue by Victor61** [DaveRandom/Resume#3]
Hi!
As far as i can see, the full filesize is always returned as Content-length. I think this is not completely compliant with the definition of 206 Partial Content (rfc7233). or am i wrong?

```
 HTTP/1.1 206 Partial Content
 Date: Thu, 05 Apr 2018 21:26:15 GMT
 Server: Apache/2.4.27 (Win64) OpenSSL/1.1.0f PHP/7.1.9
 X-Powered-By: PHP/7.1.9
 Content-Length: 1000 // currently in each response constant
 accept-ranges: bytes
 Content-Range: bytes 445-999/1000
 Content-Type: video/x-matroska
 
 ... followed by 555 bytes of partial data ...
```

shouldn't it be in this example:
`Content-Length:  555`
Which means it has to be calculated individually for each response and range?

**Comment by DaveRandom** [comment]
Apologies for the delayed action on this but I've only just got round to double checking the RFC and you are correct, this is definitely a bug, which should now be resolved.

**Comment by uniquexor** [comment]
It appears, that it is again sending the wrong Content-Length on with partial content
