### ISSUE TITLE
No support for at least PHP 5.4

### ISSUE THREAD

**Issue by MR-AMDEV** [DaveRandom/Resume#4]
Hi I am using this beautiful library and i though that this is just awesome but it would be better it this supports 5.4 as a minimum requirement.
Currently i ll be using php version to determine weather i ll use this or other classes for pp versions.
Thanks

**Comment by DaveRandom** [comment]
PHP 5 is dead, I have no plans to support PHP 5 any more in any projects :-P

Sorry
